# https://yarnpkg.com/configuration/yarnrc
nodeLinker: node-modules
# Path of a Yarn binary to use instead of the global one.
yarnPath: .yarn/releases/yarn-4.4.0.cjs
# Define the registry to use when fetching packages.
npmRegistryServer: "https://registry.yarnpkg.com"