#!/usr/bin/env node
/**
 * Bundle built-in skills from real files on disk into a TypeScript module.
 *
 * Reads every subdirectory of `src/ai-assistant-v2/skills/built-in/`, expects
 * each to contain `skill.yaml` and `SKILL.md` (plus any optional extra files),
 * and emits `src/ai-assistant-v2/skills/bundledSkills.ts` containing a
 * `BUNDLED_SKILLS` array of `SeedSkill` objects.
 *
 * Run automatically as a prebuild step (see package.json `prebuild` script),
 * or manually: `node scripts/generate-skills.mjs`
 */

import {readdirSync, readFileSync, writeFileSync, statSync} from 'node:fs';
import {join, dirname} from 'node:path';
import {fileURLToPath} from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const SKILLS_DIR = join(ROOT, 'src/ai-assistant-v2/skills/built-in');
const OUTPUT = join(ROOT, 'src/ai-assistant-v2/skills/bundledSkills.ts');
const ROOT_ID = 'built-in';

/**
 * @param {string} dir
 * @returns {{relativePath: string, content: string}[]}
 */
function readSkillFiles(dir) {
  const entries = readdirSync(dir);
  const files = [];
  for (const name of entries) {
    const fullPath = join(dir, name);
    if (statSync(fullPath).isFile()) {
      files.push({relativePath: name, content: readFileSync(fullPath, 'utf8')});
    }
  }
  return files;
}

function main() {
  const skillDirs = readdirSync(SKILLS_DIR)
    .map(name => ({name, path: join(SKILLS_DIR, name)}))
    .filter(entry => statSync(entry.path).isDirectory())
    .sort((a, b) => a.name.localeCompare(b.name));

  const seeds = skillDirs.map(({name: id, path}) => {
    const files = readSkillFiles(path);
    return {id, rootId: ROOT_ID, files};
  });

  const header = `// Auto-generated by scripts/generate-skills.mjs — DO NOT EDIT
import type {SkillFile} from '@sqlrooms/ai';

export interface BundledSeedSkill {
  id: string;
  rootId: string;
  files: SkillFile[];
}

export const BUNDLED_SKILLS: BundledSeedSkill[] = ${JSON.stringify(seeds, null, 2)};
`;

  writeFileSync(OUTPUT, header, 'utf8');
  console.log(
    `Generated ${OUTPUT} with ${seeds.length} skills: ${seeds.map(s => s.id).join(', ')}`
  );
}

main();
