// SPDX-License-Identifier: MIT
// Copyright contributors to the kepler.gl project

import {theme} from './base';

/**
 * Color palette for the space UI theme
 */
const COLOR = {
  AZURE: '#0E111A',
  AZURE950: '#161B29',
  AZURE900: '#1C2233',
  AZURE800: '#262D40',
  AZURE700: '#2E364D',
  AZURE600: '#313A52',
  AZURE500: '#363F59',
  AZURE300: '#3D4866',
  AZURE200: '#54638C',
  AZURE150: '#5C6C99',
  AZURE100: '#7A90CC',

  GREY: '#8F90BC',
  GREY20: '#D5D5E6',
  GREY10: '#ECECF3',

  BLUE: '#5558DB',
  BLUE110: '#4F52CC',

  VIOLET: '#8863F8',
  ORANGE: '#F7B26B',
  GREEN: '#4BB34B',
  RED: '#F05C44',
  RED80: 'rgba(240, 92, 68, 0.8)',

  WHITE: '#F7F8FA',
  PURE_WHITE: '#FFFFFF'
};

/**
 * Space color theme. Kepler dark layout/sizing, with azure surfaces and a blue accent.
 */
export const themeSpace = {
  ...theme,

  activeColor: COLOR.BLUE,
  activeColorHover: COLOR.BLUE110,
  secondaryActiveColor: COLOR.GREEN,
  errorColor: COLOR.RED,
  logoColor: COLOR.BLUE,
  borderColor: COLOR.AZURE900,

  textColor: COLOR.WHITE,
  textColorHl: COLOR.WHITE,
  textColorLT: COLOR.AZURE300,
  titleTextColor: COLOR.WHITE,
  subtextColor: COLOR.AZURE200,
  subtextColorLT: COLOR.AZURE200,
  subtextColorActive: COLOR.WHITE,
  labelColor: COLOR.AZURE150,
  labelColorLT: COLOR.GREY,
  labelHoverColor: COLOR.AZURE100,
  titleColorLT: COLOR.AZURE,
  fontWhiteColor: COLOR.AZURE200,

  sidePanelBg: COLOR.AZURE,
  sidePanelHeaderBg: COLOR.AZURE900,
  sideBarCloseBtnBgd: COLOR.AZURE900,
  sideBarCloseBtnColor: COLOR.WHITE,
  sideBarCloseBtnBgdHover: COLOR.AZURE800,

  panelBackground: COLOR.AZURE900,
  panelContentBackground: COLOR.AZURE950,
  panelBackgroundHover: COLOR.AZURE800,
  panelBackgroundLT: COLOR.PURE_WHITE,
  panelBorderColor: COLOR.AZURE900,
  panelBorder: `1px solid ${COLOR.AZURE900}`,
  panelHeaderIcon: COLOR.AZURE200,
  panelHeaderIconActive: COLOR.WHITE,
  panelHeaderIconHover: COLOR.WHITE,
  panelToggleBorderColor: COLOR.BLUE,
  panelTabColor: COLOR.AZURE200,
  mapPanelBackgroundColor: COLOR.AZURE,
  mapPanelHeaderBackgroundColor: COLOR.AZURE900,
  bottomWidgetBgd: COLOR.AZURE900,
  chickletBgd: COLOR.AZURE500,
  layerPanelToggleOptionColor: COLOR.AZURE200,
  layerPanelToggleOptionColorActive: COLOR.WHITE,
  layerConfiguratorBorderColor: COLOR.AZURE500,

  primaryBtnBgd: COLOR.BLUE,
  primaryBtnActBgd: COLOR.BLUE110,
  primaryBtnBgdHover: COLOR.BLUE110,
  primaryBtnColor: COLOR.WHITE,
  primaryBtnActColor: COLOR.WHITE,
  secondaryBtnBgd: COLOR.AZURE700,
  secondaryBtnColor: COLOR.WHITE,
  secondaryBtnActBgd: COLOR.AZURE600,
  secondaryBtnBgdHover: COLOR.AZURE600,
  secondaryBtnActColor: COLOR.WHITE,
  floatingBtnBgd: COLOR.AZURE900,
  floatingBtnActBgd: COLOR.AZURE800,
  floatingBtnBgdHover: COLOR.AZURE800,
  floatingBtnColor: COLOR.AZURE200,
  floatingBtnActColor: COLOR.WHITE,
  ctaBtnBgd: COLOR.BLUE110,
  ctaBtnBgdHover: COLOR.BLUE,
  ctaBtnActBgd: COLOR.BLUE,
  ctaBtnColor: COLOR.WHITE,
  ctaBtnActColor: COLOR.WHITE,
  negativeBtnBgd: COLOR.RED,
  negativeBtnActBgd: COLOR.RED80,
  negativeBtnBgdHover: COLOR.RED80,
  negativeBtnColor: COLOR.WHITE,
  negativeBtnActColor: COLOR.WHITE,
  linkBtnColor: COLOR.AZURE200,
  linkBtnActColor: COLOR.AZURE100,
  selectionBtnColor: COLOR.AZURE200,
  selectionBtnActColor: COLOR.BLUE,
  selectionBtnBorderColor: COLOR.AZURE200,
  selectionBtnBorderActColor: COLOR.BLUE,

  inputBgd: COLOR.AZURE900,
  inputColor: COLOR.WHITE,
  inputBgdHover: COLOR.AZURE800,
  inputBgdActive: COLOR.AZURE800,
  inputBorderColor: COLOR.AZURE900,
  inputBorderHoverColor: COLOR.AZURE800,
  inputBorderActiveColor: COLOR.BLUE,
  inputPlaceholderColor: COLOR.AZURE200,
  inputPlaceholderColorLT: COLOR.AZURE200,
  secondaryInputBgd: COLOR.AZURE800,
  secondaryInputColor: COLOR.WHITE,
  secondaryInputBgdActive: COLOR.AZURE700,
  secondaryInputBgdHover: COLOR.AZURE700,
  secondaryInputBorderColor: COLOR.AZURE800,
  secondaryInputBorderActiveColor: COLOR.BLUE,

  selectColor: COLOR.WHITE,
  selectColorPlaceHolder: COLOR.AZURE200,
  selectBackground: COLOR.AZURE900,
  selectBackgroundHover: COLOR.AZURE800,
  selectBorderColor: COLOR.AZURE800,
  selectBackgroundLT: COLOR.GREY10,
  selectBorderColorLT: COLOR.GREY10,
  inputBorderActiveColorLT: COLOR.BLUE,
  inputBorderHoverColorLT: COLOR.GREY20,
  inputBgdActiveLT: COLOR.GREY20,
  dropdownListBgd: COLOR.AZURE900,
  dropdownListHighlightBg: COLOR.AZURE800,
  dropdownListBorderTop: COLOR.AZURE800,
  toolbarItemBgdHover: COLOR.AZURE800,
  toolbarItemIconHover: COLOR.BLUE,

  switchTrackBgd: COLOR.AZURE800,
  secondarySwitchTrackBgd: COLOR.AZURE800,
  switchTrackBgdActive: COLOR.BLUE,
  secondarySwitchBtnBgd: COLOR.AZURE200,
  switchBtnBgd: COLOR.AZURE200,
  switchBtnBgdActive: COLOR.WHITE,

  checkboxBoxBgdChecked: COLOR.BLUE,
  checkboxBoxBgd: 'transparent',
  checkboxBorderColor: COLOR.AZURE200,

  scrollbarThumbColorLT: COLOR.AZURE200,
  scrollbarThumbColorHoverLT: COLOR.GREY,

  tooltipBg: COLOR.AZURE300,
  tooltipColor: COLOR.WHITE,

  sliderHandleColor: COLOR.WHITE,
  sliderHandleTextColor: COLOR.BLUE,
  sliderHandleHoverColor: COLOR.WHITE,
  sliderBarColor: COLOR.BLUE,
  sliderBarBgd: COLOR.AZURE900,
  sliderBarHoverColor: COLOR.AZURE100,
  rangeBrushBgd: COLOR.AZURE700,
  histogramFillInRange: COLOR.BLUE,
  histogramFillOutRange: COLOR.AZURE600,
  histogramOverlayColor: COLOR.AZURE600,
  axisFontColor: COLOR.AZURE200,

  effectPanelTextMain: COLOR.WHITE,
  effectPanelTextSecondary1: COLOR.AZURE100,
  effectPanelTextSecondary2: COLOR.AZURE200,
  effectPanelTextSecondary3: COLOR.AZURE300,
  effectPanelElementColor: COLOR.AZURE800,
  effectPanelElementColorSelected: COLOR.AZURE700,
  effectPanelElementColorActive: COLOR.AZURE300,
  effectPanelElementColorHovered: COLOR.AZURE200,
  effectPanelElementColorSun: COLOR.ORANGE,

  notificationColors: {
    info: COLOR.VIOLET,
    error: COLOR.RED,
    success: COLOR.GREEN,
    warning: COLOR.ORANGE
  },
  progressBarColor: COLOR.BLUE
};
