// SPDX-License-Identifier: MIT
// Copyright contributors to the kepler.gl project

import {ToolLoopAgent, stepCountIs, tool} from 'ai';
import {z} from 'zod';
import {streamSubAgent, AiSliceState} from '@sqlrooms/ai-core';
import {StoreApi} from '@sqlrooms/room-store';
import {KeplerContext} from '../types';
import {getGeoTools} from '../tools/geo-tools';
import {getQueryTools} from '../tools/query-tool';
import {getModel} from './model-utils';

const GEO_AGENT_INSTRUCTIONS = `You are a geospatial analysis assistant. You help users with spatial operations, geocoding, routing, and geographic data processing.

For any SQL query:
1. Only use statements, query syntax, data types, expressions, functions that are supported by DuckDB.
2. Use dbTableName in the SQL query to reference the table in the database.
3. Only first 2 rows of the result will be returned to LLM for reference.

For data analysis:
1. If new dataset has been generated by tools (buffer, centroid, isochrone, etc.):
   a. Save them as a new dataset in kepler.gl first
   b. Use the new dataset for spatial analysis
2. For using road datasets in spatial analysis:
   a. Buffer the road by 1 meter first
   b. Save the buffered road as a new dataset

For spatial filtering:
1. The leftDatasetName should be the points dataset
2. The rightDatasetName should be the polygon dataset
3. Apply the spatial filter and save the result
4. Use filterDataset to filter where Count > 0

For dataClassify tool: when classifying data into bins:
a. The lower bound is inclusive, and the upper bound is exclusive except the last bin
b. If user provides custom breaks, there is no need to call dataClassify tool

For datasetName argument:
1. Use the dataset name or dataset label, not the dataset id
`;

export function geoAgentTool(store: StoreApi<AiSliceState>, ctx: KeplerContext) {
  return tool({
    description:
      'An agent for geospatial analysis: routing, isochrones, geocoding, spatial joins, spatial filters, buffers, centroids, dissolves, US boundary data, and other geo operations.',
    inputSchema: z.object({
      reasoning: z.string().describe('Reasoning for why this agent is being called'),
      prompt: z.string().describe('The geospatial analysis request')
    }),
    execute: async ({prompt}, options?: {toolCallId?: string; abortSignal?: AbortSignal}) => {
      const geoTools = getGeoTools(ctx);
      const queryTools = getQueryTools(ctx);
      const tools = {
        ...geoTools,
        ...queryTools
      };
      const agent = new ToolLoopAgent({
        model: getModel(store),
        instructions: GEO_AGENT_INSTRUCTIONS,
        tools,
        stopWhen: stepCountIs(15)
      });

      const result = await streamSubAgent(
        agent,
        prompt,
        store,
        options?.toolCallId || '',
        options?.abortSignal
      );

      return {
        success: true,
        finalOutput: result.finalOutput
      };
    }
  });
}
